// Barrel exports for shared constants.
export {
  clampTooltipDelay,
  DEFAULT_TOOLTIP_DELAY_MS,
  FILE_TOOLTIP_DELAY_MS,
  TOOLTIP_CACHE_LIMIT,
  TOOLTIP_EDGE_PADDING,
  TOOLTIP_GAP,
} from "./tooltip";
export {
  APP_DESCRIPTION,
  APP_ISSUES_URL,
  APP_NAME,
  APP_REPO_URL,
  APP_VERSION,
} from "./app";
export { FILE_SHEET_PATH } from "./assets";
export { IMAGE_CONVERT_EXTENSIONS, VIDEO_CONVERT_EXTENSIONS } from "./convert";
export {
  ARCHIVE_EXTENSIONS,
  AUDIO_EXTENSIONS,
  DOCUMENT_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  PDF_LIKE_EXTENSIONS,
  SECURE_EXTENSIONS,
  SVG_LIKE_EXTENSIONS,
  VIDEO_EXTENSIONS,
} from "./fileKinds";
export { MAX_ICON_BATCH } from "./fileIcons";
export {
  DRAG_SUPPRESS_TIMEOUT_MS,
  DRAG_THRESHOLD_PX,
} from "./drag";
export {
  DEFAULT_SNAP_PX,
  DEFAULT_TYPING_RESET_MS,
  DIR_CHANGE_DEBOUNCE_MS,
  ENTRY_FADE_IN_MS,
  ENTRY_FADE_OUT_MS,
  LEGACY_TICK_DELTA,
  LINE_TICK_DELTA,
  MAX_SCROLL_RESTORE_ATTEMPTS,
  META_REQUEST_DELAY_MS,
  PAGE_TICK_DELTA,
  PIXEL_TICK_DELTA,
  PREFETCH_INTERVAL_MS,
  REFRESH_COOLDOWN_MS,
  SETTLE_MS,
  TAB_SWITCH_CHECK_DELAY_MS,
  TAB_SWITCH_REFRESH_COOLDOWN_MS,
  THUMB_EVENT_FLUSH_MS,
  THUMB_REQUEST_DELAY_MS,
  TYPEAHEAD_RESET_MS,
  WINDOW_MAX_SIZE,
  WINDOW_MIN_SIZE,
  WINDOW_PERSIST_DELAY_MS,
  WINDOW_STORAGE_KEY,
  WINDOW_STORAGE_VERSION,
} from "./perf";
export {
  DIR_CACHE_LIMIT,
  FAST_SORT_THRESHOLD,
  META_CACHE_LIMIT,
  META_FLUSH_INTERVAL_MS,
  THUMB_INTERACTION_COOLDOWN_MS,
  THUMB_TYPING_PAUSE_MS,
  UNDO_STACK_LIMIT,
} from "./fs";
export {
  SESSION_LEGACY_STORAGE_KEY,
  SESSION_STORAGE_KEY,
  SESSION_STORAGE_VERSION,
} from "./session";
export {
  GRID_AUTO_COLUMNS_DEFAULT,
  GRID_AUTO_COLUMNS_MAX,
  GRID_AUTO_COLUMNS_MIN,
  GRID_GAP_DEFAULT,
  GRID_GAP_MAX,
  GRID_GAP_MIN,
  SETTINGS_STORAGE_KEY,
  SETTINGS_STORAGE_VERSION,
  SIDEBAR_RECENT_LIMIT_MAX,
  SIDEBAR_RECENT_LIMIT_MIN,
} from "./settings";
export {
  DEFAULT_KEYBINDS,
  KEYBIND_DEFINITIONS,
  MODIFIER_KEYS,
  MODIFIER_ORDER,
  PRIMARY_MODIFIERS,
  RESERVED_KEYBIND_DEFINITIONS,
  RESERVED_KEYBINDS,
  SINGLE_CHAR_PATTERN,
} from "./keybinds";
export type { KeybindAction, KeybindDefinition, KeybindMap } from "./keybinds";
export { CONTEXT_MENU_EDGE, CONTEXT_MENU_GAP, CONTEXT_SUBMENU_GAP } from "./menus";
